/// <reference types="vite/client" />
/**
 * QuranService - offline-first access layer for the vendored Mushaf dataset.
 *
 * Data is bundled statically under data/static/quran/. The surah index and
 * the juz start table are loaded eagerly (~20 KB combined); per-surah Uthmani
 * text and Tafsir Muyassar files are loaded on demand via import.meta.glob so
 * the initial bundle stays small.
 *
 * Audio recitation is streamed from cdn.islamic.network; URLs follow the
 * convention documented at https://alquran.cloud and accept the same global
 * ayah numbering (1..6236) that is bundled in each row of text/{n}.json.
 */

import surahIndex from '../data/static/quran/index.json';
import juzStarts from '../data/static/quran/juz.json';

// Vite splits each surah body and each tafsir payload into its own JS chunk;
// the user pays the cost only when a surah is actually opened.
const textLoaders = import.meta.glob<{ s: number; a: AyatRow }>(
    '../data/static/quran/text/*.json'
);
const tafsirLoaders = import.meta.glob<string[]>(
    '../data/static/quran/tafsir/*.json'
);

// --- Types ---------------------------------------------------------------

export interface SurahMeta {
    id: number;
    name: string;
    transliteration: string;
    meaning: string;
    revelation: 'مكية' | 'مدنية';
    ayahCount: number;
    firstPage: number;
}

/**
 * Compact row layout generated by scripts/generate-quran-data.mjs:
 *   [ numberInSurah, uthmaniText, madaniPage, juz, sajda, globalNumber ]
 *   sajda is encoded as 0 = none, 1 = recommended, 2 = obligatory
 */
export type AyatRow = [number, string, number, number, 0 | 1 | 2, number];

export interface QuranAyah {
    number: number;          // 1-based within surah
    text: string;            // Uthmani script (basmala stripped from first ayah of non-Fatiha non-Tawbah surahs)
    page: number;            // Madini mushaf page
    juz: number;             // 1..30
    sajda: 0 | 1 | 2;
    globalNumber: number;    // 1..6236 - feeds the recitation CDN
    surahId: number;
}

export interface JuzStart {
    juz: number;
    surah: number;
    ayah: number;
}

export interface Reciter {
    id: string;          // identifier expected by cdn.islamic.network
    name: string;        // Arabic display name
    style: string;       // short description
}

// --- Static catalogues ---------------------------------------------------

/**
 * Reciters verified reachable on cdn.islamic.network at the time of audit.
 * Add only after probing https://cdn.islamic.network/quran/audio/128/<id>/1.mp3
 * with HEAD and confirming 200 OK.
 */
export const RECITERS: Reciter[] = [
    { id: 'ar.alafasy',      name: 'مشاري العفاسي',         style: 'مرتل' },
    { id: 'ar.husary',       name: 'محمود خليل الحصري',     style: 'مرتل' },
    { id: 'ar.minshawi',     name: 'محمد صديق المنشاوي',     style: 'مرتل' },
    { id: 'ar.hudhaify',     name: 'علي الحذيفي',            style: 'مرتل' },
    { id: 'ar.mahermuaiqly', name: 'ماهر المعيقلي',          style: 'مرتل' },
];

export const SURAHS: ReadonlyArray<SurahMeta> = surahIndex as SurahMeta[];
export const JUZ_STARTS: ReadonlyArray<JuzStart> = juzStarts as JuzStart[];

// --- Lazy loaders --------------------------------------------------------

const textCache = new Map<number, QuranAyah[]>();
const tafsirCache = new Map<number, string[]>();

/** Loads (and memoises) the full Uthmani text of a surah. */
export async function loadSurah(surahId: number): Promise<QuranAyah[]> {
    const hit = textCache.get(surahId);
    if (hit) return hit;
    const loader = textLoaders['../data/static/quran/text/' + surahId + '.json'];
    if (!loader) throw new Error('QuranService: unknown surah ' + surahId);
    const mod = await loader();
    const rows = mod.a as unknown as AyatRow[];
    const ayahs: QuranAyah[] = rows.map(row => ({
        number: row[0],
        text: row[1],
        page: row[2],
        juz: row[3],
        sajda: row[4],
        globalNumber: row[5],
        surahId,
    }));
    textCache.set(surahId, ayahs);
    return ayahs;
}

/** Loads (and memoises) the Tafsir Muyassar for a surah, index-aligned to ayahs. */
export async function loadTafsir(surahId: number): Promise<string[]> {
    const hit = tafsirCache.get(surahId);
    if (hit) return hit;
    const loader = tafsirLoaders['../data/static/quran/tafsir/' + surahId + '.json'];
    if (!loader) throw new Error('QuranService: unknown surah ' + surahId);
    const arr = await loader();
    tafsirCache.set(surahId, arr);
    return arr;
}

// --- Position helpers ----------------------------------------------------

/** Cached table mapping global ayah number (1..6236) to { surah, ayah }. */
let positionTable: Array<{ surah: number; ayah: number }> | null = null;
function getPositionTable(): Array<{ surah: number; ayah: number }> {
    if (positionTable) return positionTable;
    let offset = 0;
    const map = new Array<{ surah: number; ayah: number }>(6236);
    for (const s of SURAHS) {
        for (let a = 1; a <= s.ayahCount; a++) {
            map[offset + a - 1] = { surah: s.id, ayah: a };
        }
        offset += s.ayahCount;
    }
    positionTable = map;
    return map;
}

export function positionFromGlobal(globalNumber: number): { surah: number; ayah: number } {
    const map = getPositionTable();
    if (globalNumber < 1 || globalNumber > map.length) {
        throw new Error('QuranService: global ayah out of range: ' + globalNumber);
    }
    return map[globalNumber - 1];
}

// --- Search --------------------------------------------------------------

/**
 * Arabic-aware normalisation used everywhere a free-text match is needed.
 *  - strips harakat, tatweel, Quranic annotation marks
 *  - unifies alef/hamza wasla forms
 *  - folds ya/alef-maqsura and ta marbuta for loose matching
 *  - lowercases for transliteration lookups
 */
export function normalizeArabic(input: string): string {
    return input
        .normalize('NFKC')
        .replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED\u0640]/g, '')
        .replace(/[\u0622\u0623\u0625\u0671]/g, '\u0627')
        .replace(/\u0649/g, '\u064A')
        .replace(/\u0629/g, '\u0647')
        .replace(/\s+/g, ' ')
        .trim()
        .toLowerCase();
}

export interface SurahSearchResult extends SurahMeta {
    /** Lower is better: closest match to the query start. */
    position: number;
}

/**
 * Substring match across Arabic name, transliteration, meaning, and the
 * numeric id. Empty query returns every surah (ordered by id).
 */
export function searchSurahs(query: string): SurahMeta[] {
    const trimmed = query.trim();
    if (!trimmed) return [...SURAHS];
    const needle = normalizeArabic(trimmed);
    const results: SurahSearchResult[] = [];
    for (const s of SURAHS) {
        const candidates = [
            normalizeArabic(s.name),
            normalizeArabic(s.transliteration),
            normalizeArabic(s.meaning),
            String(s.id),
            normalizeArabic('\u0633\u0648\u0631\u0629 ' + s.id),
        ];
        let best = -1;
        for (const c of candidates) {
            const idx = c.indexOf(needle);
            if (idx >= 0 && (best < 0 || idx < best)) best = idx;
        }
        if (best >= 0) results.push({ ...s, position: best });
    }
    results.sort((a, b) => a.position - b.position || a.id - b.id);
    return results;
}

// --- Audio URLs ----------------------------------------------------------

/** Builds the per-ayah MP3 URL used by cdn.islamic.network. */
export function ayahAudioUrl(reciterId: string, globalAyahNumber: number): string {
    return 'https://cdn.islamic.network/quran/audio/128/' +
        encodeURIComponent(reciterId) + '/' + globalAyahNumber + '.mp3';
}

/** Surah-level MP3 (large files; useful for continuous play). */
export function surahAudioUrl(reciterId: string, surahId: number): string {
    return 'https://cdn.islamic.network/quran/audio-surah/128/' +
        encodeURIComponent(reciterId) + '/' + surahId + '.mp3';
}

/** Number -> Arabic-Indic numeral, used for in-line ayah markers. */
export function toArabicDigits(n: number): string {
    return n.toString().replace(/\d/g, d =>
        '\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669'[+d]);
}

export function getSurah(surahId: number): SurahMeta | undefined {
    return SURAHS.find(s => s.id === surahId);
}

export function getJuzStart(juz: number): JuzStart | undefined {
    return JUZ_STARTS.find(j => j.juz === juz);
}

/**
 * True for surahs that need a decorative Bismillah header rendered above ayah 1:
 *   Al-Fatiha (1) -> basmala IS ayah 1, no separate header
 *   At-Tawbah  (9) -> no bismillah at all
 */
export function showsBismillahHeader(surahId: number): boolean {
    return surahId !== 1 && surahId !== 9;
}

/** Total number of ayahs in the Mushaf (6236 for the Hafs reading). */
export function totalAyat(): number {
    return SURAHS.reduce((sum, s) => sum + s.ayahCount, 0);
}
