/// <reference types="vite/client" />
/**
 * QuranService - offline-first access layer for the vendored Mushaf dataset.
 *
 * Data is bundled statically under data/static/quran/. The surah index and
 * the juz start table are loaded eagerly (~20 KB combined); per-surah Uthmani
 * text and Tafsir Muyassar files are loaded on demand via import.meta.glob so
 * the initial bundle stays small.
 *
 * Audio recitation is streamed from cdn.islamic.network; URLs follow the
 * convention documented at https://alquran.cloud and accept the same global
 * ayah numbering (1..6236) that is bundled in each row of text/{n}.json.
 */

import surahIndex from '../data/static/quran/index.json';
import juzStarts from '../data/static/quran/juz.json';

// Re-exported so callers that already import the service can also reach the
// MushafMode type without taking a second import line.
export type { MushafMode } from '../types';

// Vite splits each surah body and each tafsir payload into its own JS chunk;
// the user pays the cost only when a surah is actually opened.
const textLoaders = import.meta.glob<{ s: number; a: AyatRow }>(
    '../data/static/quran/text/*.json'
);
const tafsirLoaders = import.meta.glob<string[]>(
    '../data/static/quran/tafsir/*.json'
);

// --- Types ---------------------------------------------------------------

export interface SurahMeta {
    id: number;
    name: string;
    transliteration: string;
    meaning: string;
    revelation: 'مكية' | 'مدنية';
    ayahCount: number;
    firstPage: number;
}

/**
 * Compact row layout generated by scripts/generate-quran-data.mjs:
 *   [ numberInSurah, uthmaniText, madaniPage, juz, sajda, globalNumber ]
 *   sajda is encoded as 0 = none, 1 = recommended, 2 = obligatory
 */
export type AyatRow = [number, string, number, number, 0 | 1 | 2, number];

export interface QuranAyah {
    number: number;          // 1-based within surah
    text: string;            // Uthmani script (basmala stripped from first ayah of non-Fatiha non-Tawbah surahs)
    page: number;            // Madini mushaf page
    juz: number;             // 1..30
    sajda: 0 | 1 | 2;
    globalNumber: number;    // 1..6236 - feeds the recitation CDN
    surahId: number;
}

export interface JuzStart {
    juz: number;
    surah: number;
    ayah: number;
}

// Reciters moved to data/static/reciters.json (M1-T4). The bundled verified
// catalog plus the Wi-Fi-gated additive refresh channel live in
// reciterCatalog.ts (getReciters/getReciter/refreshRecitersIfWifi).
export type { Reciter } from './reciterCatalog';

export const SURAHS: ReadonlyArray<SurahMeta> = surahIndex as SurahMeta[];
export const JUZ_STARTS: ReadonlyArray<JuzStart> = juzStarts as JuzStart[];

// --- Lazy loaders --------------------------------------------------------

const textCache = new Map<number, QuranAyah[]>();
const tafsirCache = new Map<number, string[]>();

/** Loads (and memoises) the full Uthmani text of a surah. */
export async function loadSurah(surahId: number): Promise<QuranAyah[]> {
    const hit = textCache.get(surahId);
    if (hit) return hit;
    const loader = textLoaders['../data/static/quran/text/' + surahId + '.json'];
    if (!loader) throw new Error('QuranService: unknown surah ' + surahId);
    const mod = await loader();
    const rows = mod.a as unknown as AyatRow[];
    const ayahs: QuranAyah[] = rows.map(row => ({
        number: row[0],
        text: row[1],
        page: row[2],
        juz: row[3],
        sajda: row[4],
        globalNumber: row[5],
        surahId,
    }));
    textCache.set(surahId, ayahs);
    return ayahs;
}

/** Loads (and memoises) the Tafsir Muyassar for a surah, index-aligned to ayahs. */
export async function loadTafsir(surahId: number): Promise<string[]> {
    const hit = tafsirCache.get(surahId);
    if (hit) return hit;
    const loader = tafsirLoaders['../data/static/quran/tafsir/' + surahId + '.json'];
    if (!loader) throw new Error('QuranService: unknown surah ' + surahId);
    const arr = await loader();
    tafsirCache.set(surahId, arr);
    return arr;
}

// --- Position helpers ----------------------------------------------------

/** Cached table mapping global ayah number (1..6236) to { surah, ayah }. */
let positionTable: Array<{ surah: number; ayah: number }> | null = null;
function getPositionTable(): Array<{ surah: number; ayah: number }> {
    if (positionTable) return positionTable;
    let offset = 0;
    const map = new Array<{ surah: number; ayah: number }>(6236);
    for (const s of SURAHS) {
        for (let a = 1; a <= s.ayahCount; a++) {
            map[offset + a - 1] = { surah: s.id, ayah: a };
        }
        offset += s.ayahCount;
    }
    positionTable = map;
    return map;
}

export function positionFromGlobal(globalNumber: number): { surah: number; ayah: number } {
    const map = getPositionTable();
    if (globalNumber < 1 || globalNumber > map.length) {
        throw new Error('QuranService: global ayah out of range: ' + globalNumber);
    }
    return map[globalNumber - 1];
}

/** Reverse of positionFromGlobal: (surahId, ayahInSurah) -> global 1..6236.
 *  Used by the app-level player, which only knows the (surah, ayah) command. */
export function globalAyahNumber(surahId: number, ayahInSurah: number): number {
    let offset = 0;
    for (const s of SURAHS) {
        if (s.id === surahId) {
            if (ayahInSurah < 1 || ayahInSurah > s.ayahCount) {
                throw new Error('QuranService: ayah out of range: ' + surahId + ':' + ayahInSurah);
            }
            return offset + ayahInSurah;
        }
        offset += s.ayahCount;
    }
    throw new Error('QuranService: unknown surah ' + surahId);
}

// --- Search --------------------------------------------------------------

/**
 * Arabic-aware normalisation used everywhere a free-text match is needed.
 *  - strips harakat, tatweel, Quranic annotation marks
 *  - unifies alef/hamza wasla forms
 *  - folds ya/alef-maqsura and ta marbuta for loose matching
 *  - lowercases for transliteration lookups
 */
export function normalizeArabic(input: string): string {
    return input
        .normalize('NFKC')
        .replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED\u0640]/g, '')
        .replace(/[\u0622\u0623\u0625\u0671]/g, '\u0627')
        .replace(/\u0649/g, '\u064A')
        .replace(/\u0629/g, '\u0647')
        .replace(/\s+/g, ' ')
        .trim()
        .toLowerCase();
}

export interface SurahSearchResult extends SurahMeta {
    /** Lower is better: closest match to the query start. */
    position: number;
}

/**
 * Substring match across Arabic name, transliteration, meaning, and the
 * numeric id. Empty query returns every surah (ordered by id).
 */
export function searchSurahs(query: string): SurahMeta[] {
    const trimmed = query.trim();
    if (!trimmed) return [...SURAHS];
    const needle = normalizeArabic(trimmed);
    const results: SurahSearchResult[] = [];
    for (const s of SURAHS) {
        const candidates = [
            normalizeArabic(s.name),
            normalizeArabic(s.transliteration),
            normalizeArabic(s.meaning),
            String(s.id),
            normalizeArabic('\u0633\u0648\u0631\u0629 ' + s.id),
        ];
        let best = -1;
        for (const c of candidates) {
            const idx = c.indexOf(needle);
            if (idx >= 0 && (best < 0 || idx < best)) best = idx;
        }
        if (best >= 0) results.push({ ...s, position: best });
    }
    results.sort((a, b) => a.position - b.position || a.id - b.id);
    return results;
}

// --- Audio URLs ----------------------------------------------------------

/** Builds the per-ayah MP3 URL used by cdn.islamic.network. */
export function ayahAudioUrl(reciterId: string, globalAyahNumber: number): string {
    return 'https://cdn.islamic.network/quran/audio/128/' +
        encodeURIComponent(reciterId) + '/' + globalAyahNumber + '.mp3';
}

/** Surah-level MP3 (large files; useful for continuous play). */
export function surahAudioUrl(reciterId: string, surahId: number): string {
    return 'https://cdn.islamic.network/quran/audio-surah/128/' +
        encodeURIComponent(reciterId) + '/' + surahId + '.mp3';
}

/** Number -> Arabic-Indic numeral, used for in-line ayah markers. */
export function toArabicDigits(n: number): string {
    return n.toString().replace(/\d/g, d =>
        '\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669'[+d]);
}

export function getSurah(surahId: number): SurahMeta | undefined {
    return SURAHS.find(s => s.id === surahId);
}

export function getJuzStart(juz: number): JuzStart | undefined {
    return JUZ_STARTS.find(j => j.juz === juz);
}

/**
 * True for surahs that need a decorative Bismillah header rendered above ayah 1:
 *   Al-Fatiha (1) -> basmala IS ayah 1, no separate header
 *   At-Tawbah  (9) -> no bismillah at all
 */
export function showsBismillahHeader(surahId: number): boolean {
    return surahId !== 1 && surahId !== 9;
}

/** Total number of ayahs in the Mushaf (6236 for the Hafs reading). */
export function totalAyat(): number {
    return SURAHS.reduce((sum, s) => sum + s.ayahCount, 0);
}

/** Total number of Madinah Mushaf pages (604 for the standard Hafs layout). */
export const TOTAL_MUSHAF_PAGES = 604;

/** Lazy page -> [QuranAyah] index, built once on first call. Walks every
 *  surah's text row and groups by the `page` field, so lookups are O(1) and
 *  a page render never has to scan 114 files again. */
let pageIndex: Map<number, QuranAyah[]> | null = null;

async function buildPageIndex(): Promise<Map<number, QuranAyah[]>> {
    if (pageIndex) return pageIndex;
    const idx = new Map<number, QuranAyah[]>();
    for (const s of SURAHS) {
        const arr = await loadSurah(s.id);
        for (const a of arr) {
            const bucket = idx.get(a.page);
            if (bucket) bucket.push(a);
            else idx.set(a.page, [a]);
        }
    }
    pageIndex = idx;
    return idx;
}

/** Resets the lazy page index (test-only; production never mutates it). */
export function _resetPageIndexForTests(): void {
    pageIndex = null;
}

/** All ayahs that share the given Madinah Mushaf page number, ordered by
 *  surah/ayah. Returns [] if `page` is out of range. */
export async function getPageAyahs(page: number): Promise<QuranAyah[]> {
    if (page < 1 || page > TOTAL_MUSHAF_PAGES) return [];
    const idx = await buildPageIndex();
    return idx.get(page) ?? [];
}

/** Surah ids that appear on a given page, in order, deduped.
 *  Used to draw the page footer ("العصر | 601 | التين") and to detect
 *  mid-page surah changes that need a Bismillah + ornament header. */
export function getPageSurahIds(ayahs: QuranAyah[]): number[] {
    const seen = new Set<number>();
    const out: number[] = [];
    for (const a of ayahs) {
        if (!seen.has(a.surahId)) {
            seen.add(a.surahId);
            out.push(a.surahId);
        }
    }
    return out;
}
